# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia

os:
  - linux
  - osx

julia:
  - 0.7
  - 1.0
  - 1.1
  - nightly

matrix:
   allow_failures:
     - julia: 1.0
     - julia: 1.1
     - julia: nightly

notifications:
  email: false

after_success:
# build documentation
  - julia -e 'using Pkg; Pkg.add("Documenter"); cd(Pkg.dir("TaylorModels")); include(joinpath("docs", "make.jl"))'
# push coverage results to Codecov
  - julia -e 'cd(Pkg.dir("TaylorModels")); Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder()); Codecov.submit(process_folder())'
